# Generated by Django 5.0.6 on 2024-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(default='', error_messages={'unique': 'The phone_number must be unique'}, max_length=11, unique=True),
        ),
    ]
